### ISSUE TITLE
Cannot authenticate with Glow

### ISSUE THREAD

**Issue by EDIflyer** [HandyHat/ha-hildebrandglow-dcc#73] opened 2021-11-08 22:10 UTC
**Describe the bug**
Try to login to Glow - receive an error (screenshot below)

**To Reproduce**
1. Install Hildebrand Glow (DCC) Integration via HACS
2. Restart HA
3. Config > Integration > Add Integration > pick Glow
4. Receive login popup
5. Unable to login

**Expected behaviour**
To be able to login to Glow

**Screenshots**
![image](https://user-images.githubusercontent.com/13610277/140825510-4d77eb5e-0bb5-42a7-bc49-b235baaee7a6.png)

**Version**
Integration 0.5.1
HA 2021.11.1

**Debug log**
```
This error originated from a custom integration.

Logger: custom_components.hildebrandglow_dcc.config_flow
Source: custom_components/hildebrandglow_dcc/glow.py:46
Integration: Hildebrand Glow (DCC) (documentation, issues)
First occurred: 22:10:16 (1 occurrences)
Last logged: 22:10:16

Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/hildebrandglow_dcc/config_flow.py", line 60, in async_step_user
    info = await validate_input(self.hass, user_input)
  File "/config/custom_components/hildebrandglow_dcc/config_flow.py", line 37, in validate_input
    glow = await hass.async_add_executor_job(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/hildebrandglow_dcc/glow.py", line 46, in authenticate
    response = requests.http.post(url, json=auth, headers=headers)
AttributeError: module 'requests' has no attribute 'http'
```

**Additional context**
Could this be related to bug #69?

**Comment by ColinRobbins** [comment] 2021-11-08 22:34
This has been fixed in 0.5.2.

**Comment by EDIflyer** [comment] 2021-11-08 22:36
@ColinRobbins ah, great - how do I get hold of it? 0.5.1 seemed to be the latest listed version on Github?

**Comment by si458** [comment] 2021-11-08 23:34
Duplicate of my issue #69

**Comment by EDIflyer** [comment] 2021-11-08 23:38
> Duplicate of my issue #69
> 
> Just waiting for a new release from @HandyHat 😀

Yep I suspected it might be but it had been closed so I couldn't add to it and I wasn't sure if it was the same or not as it looked like it had been sorted in 0.5.1.  Excited to try it out tho - have got my accounts all approved in Glow :)

**Comment by ColinRobbins** [comment] 2021-11-09 07:27
Re-installing should pick up 0.5.2, even though not yet tagged as a release.

**Comment by EDIflyer** [comment] 2021-11-10 22:09
Fantastic, thanks @ColinRobbins - logged in fine now! Just need to start playing about with options/capabilities now :)

**Comment by megakid** [comment] 2021-11-12 23:05
Appreciate the work around before 0.52 is tagged. Thanks!

**Comment by HandyHat** [comment] 2021-11-13 19:03
Apologies - v0.5.2 has now been actually released!
FYI you can install the main branch via HACS rather than needing to manually edit the file.

Duplicate of #69

**Closed by HandyHat** 2021-11-13 19:03 UTC
Labels: bug
