### ISSUE TITLE
Gas Consumption (Year) - reading 0KWH since 27/01/22

### ISSUE THREAD

**Issue by tmh88** [HandyHat/ha-hildebrandglow-dcc#123] opened 2022-01-31 20:49 UTC
Not sure if this is a bug or an issue with Hilderbrands API.

just wondered if anyone else’s gas consumption (yearly) is now reading 0KWH?

Does it work using the daily total, as in the readme file suggests using the yearly total. It’s been fine up to now

Thanks

**Comment by JAD92** [comment] 2022-01-31 20:55
Hi, yes can confirm that my yearly gas is reading zero. 
My energy card stopped showing data since 29/01 for gas. 
Can provide screenshots or other information if required. 
The bright app shows gas usage since 29/01.

**Comment by Davecl** [comment] 2022-01-31 21:26
Mine seems ok, but I'm using daily not yearly

**Comment by redford-jones** [comment] 2022-02-01 12:05
Same issue here, although not just gas, electricity data too. It seems that Glowmarkt are having some connectivity issues that might be affecting their API because I can't even log in to the Bright app or even go to https://glowmarkt.com/

Forum discussion here: https://forum.glowmarkt.com/index.php?p=/discussion/129/bright-outage-including-apis-and-mqtt

**Comment by pid20** [comment] 2022-02-01 16:41
Glad it's not just me, been having issues the last 24 hours, unable to pull data and the app is well and truly broken

**Comment by ColinRobbins** [comment] 2022-02-01 18:15
This is definitely a problem at the Glow end, there is nothing this integration can do.
If you look at your log files you will see messages of the form…
```This error originated from a custom integration.

Logger: custom_components.hildebrandglow_dcc.glow
Source: custom_components/hildebrandglow_dcc/glow.py:133 
Integration: Hildebrand Glow (DCC) (documentation, issues) 
First occurred: 31 January 2022, 18:53:01 (65 occurrences) 
Last logged: 17:48:52

Glow response status code: 500 (https://api.glowmarkt.com/api/v0-1/resource/…

```

Status code 500 means “the server encountered an unexpected condition that prevented it from fulfilling the request.”

**Comment by alexhildebrand** [comment] 2022-02-01 18:16
https://forum.glowmarkt.com/index.php?p=/discussion/129/bright-outage-including-apis-and-mqtt#latest

**Comment by tmh88** [comment] 2022-02-01 19:10
> Mine seems ok, but I'm using daily not yearly

@Davecl 

Trying a temporary fix until hildebrand sort the gas consumption yearly issue, I have tried setting it to daily consumption and that picks up the kwh usage but dosent calculate a cost in the energy tab in HA. Dose yours? And if so, how have you got it setup? Thanks

**Comment by ColinRobbins** [comment] 2022-02-01 19:17
It will unlikely make any difference using daily versus yearly, as the server will likely fail on both.   It will also probably confuse the long term stats in HA.
My advice - be patient and wait for Glow to fix it - they are aware of the issue.

**Comment by ColinRobbins** [comment] 2022-02-02 16:21
Mine has started working again, since about 12:00 today,

**Comment by nytram-md** [comment] 2022-02-03 09:39
still missing electric yearly energy on mine but looking at the Bright App, they only go up to monthly. Are they not doing yearly now ?

Gas shows up to monthly also but Gas is now fine in HA

![image](https://user-images.githubusercontent.com/55548608/152315331-a4885f4e-e004-4da1-8d15-4027fe86dc7c.png)

**Comment by Dinth** [comment] 2022-02-06 15:45
Im getting the following - it only works between 5am - 6am every day.

Error connecting to Glow HTTPSConnectionPool(host='api.glowmarkt.com', port=443): Max retries exceeded with url: /api/v0-1/resource/8f558ac8-20da-45bf-bc57-9c8a0a8481bc/catchup (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9ea35178b0>: Failed to establish a new connection: [Errno 110] Operation timed out'))

**Comment by ColinRobbins** [comment] 2022-02-06 16:40
Its a Glow issue.
https://forum.glowmarkt.com/index.php?p=/discussion/129/bright-outage-including-apis-and-mqtt#latest

**Comment by ColinRobbins** [comment] 2022-02-07 19:01
See https://github.com/HandyHat/ha-hildebrandglow-dcc/issues/126#issuecomment-1031810136

**Comment by ColinRobbins** [comment] 2022-02-08 19:13
It seems to be working for me now - glow have fixed it.

**Comment by HandyHat** [comment] 2022-02-22 23:57
Duplicate of #126

**Closed by HandyHat** 2022-02-22 23:57 UTC
Labels: bug
