### ISSUE TITLE
API unstable - alternative approach.

### ISSUE THREAD

**Issue by ColinRobbins** [HandyHat/ha-hildebrandglow-dcc#243] opened 2022-07-31 07:19 UTC
**Is your feature request related to a problem? Please describe.**
The Glow API is unstable, and partly blamed on "agressive polling" from the Open Source community.
There is a realsitic possibilty they API will be removed.
I wonder if there is a better way from this integration to work?

**Describe the solution you'd like**
One of the issues is the repeated requests for Daily and Annual readings - which Glow say has a heavy processing cost.

In this integration, we could just read the actual & current meter reading.
The energy integration should work fine off the meter reading.

Users that want the daily and annual calculations could use the [utility meter](https://www.home-assistant.io/integrations/utility_meter/) integration.

It would be a breaking change - removing the today & annual sensors, but would push down a less "aggressive polling" approach.

**Describe alternatives you've considered**
Carry on regardless and hope Glow fix it their end.

**Comment by HandyHat** [comment] 2022-08-17 11:21
Unfortunately as described here: https://docs.glowmarkt.com/GlowmarktAPIDataRetrievalDocumentationIndividualUserForBright.pdf
meter reading and current consumption are not available via the DCC, as the data is always delayed by 30 mins.

The changes in #191 should reduce the load on the API - I just need to find time to implement them.

Duplicate of #116

**Closed by HandyHat** 2022-08-17 11:21 UTC
Labels: enhancement
