### ISSUE TITLE
Lost all Data and after new update Log Errors

### ISSUE THREAD

**Issue by thorrrr** [HandyHat/ha-hildebrandglow-dcc#127] opened 2022-02-03 10:26 UTC
Starting 3 days ago no data coming from your app energy graphs were just blank.
I have updated to 2022.2 and app showing all over logs as errors

2022-02-03 09:51:15 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration sonoff which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-02-03 09:51:15 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration shopping_list which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-02-03 09:51:15 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration alexa_media which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-02-03 09:51:15 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration remote_homeassistant which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-02-03 09:51:15 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration meross_lan which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-02-03 09:51:15 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration hildebrandglow_dcc which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-02-03 09:51:15 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-02-03 09:51:15 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration webrtc which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-02-03 09:51:15 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration magic_areas which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-02-03 09:51:15 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration dwains_dashboard which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-02-03 09:51:15 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration garbage_collection which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-02-03 09:51:15 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration fontawesome which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-02-03 09:51:15 WARNING (SyncWorker_4) [homeassistant.loader] We found a custom integration xiaomi_cloud_map_extractor which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-02-03 09:51:17 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140276770678960] Received invalid command: energy/info
2022-02-03 09:51:20 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140276768971840] Received invalid command: mobile_app/push_notification_channel
2022-02-03 09:51:29 WARNING (MainThread) [homeassistant.components.statistics.sensor] The configuration parameter 'state_characteristic' will become mandatory in a future release of the statistics integration. Please add 'state_characteristic: mean' to the configuration of sensor 'galley_average_light' to keep the current behavior. Read the documentation for further details: https://www.home-assistant.io/integrations/statistics/
2022-02-03 09:51:29 WARNING (MainThread) [homeassistant.components.statistics.sensor] The configuration parameter 'state_characteristic' will become mandatory in a future release of the statistics integration. Please add 'state_characteristic: mean' to the configuration of sensor 'hallway_average_light' to keep the current behavior. Read the documentation for further details: https://www.home-assistant.io/integrations/statistics/
2022-02-03 09:51:29 WARNING (MainThread) [homeassistant.components.statistics.sensor] The configuration parameter 'state_characteristic' will become mandatory in a future release of the statistics integration. Please add 'state_characteristic: mean' to the configuration of sensor 'living_average_light' to keep the current behavior. Read the documentation for further details: https://www.home-assistant.io/integrations/statistics/
2022-02-03 09:51:29 WARNING (MainThread) [homeassistant.components.statistics.sensor] The configuration parameter 'state_characteristic' will become mandatory in a future release of the statistics integration. Please add 'state_characteristic: mean' to the configuration of sensor 'master_bedroom_average_light' to keep the current behavior. Read the documentation for further details: https://www.home-assistant.io/integrations/statistics/
2022-02-03 09:51:29 WARNING (MainThread) [homeassistant.components.statistics.sensor] The configuration parameter 'state_characteristic' will become mandatory in a future release of the statistics integration. Please add 'state_characteristic: mean' to the configuration of sensor 'office_average_light' to keep the current behavior. Read the documentation for further details: https://www.home-assistant.io/integrations/statistics/
2022-02-03 09:51:29 WARNING (MainThread) [homeassistant.components.statistics.sensor] The configuration parameter 'state_characteristic' will become mandatory in a future release of the statistics integration. Please add 'state_characteristic: mean' to the configuration of sensor 'stairs_average_light' to keep the current behavior. Read the documentation for further details: https://www.home-assistant.io/integrations/statistics/
2022-02-03 09:51:32 WARNING (MainThread) [custom_components.meross_lan] MerossDevice(2009223902001190831148e1e9344bb8) error in async_http_request: Server disconnected
2022-02-03 09:51:32 WARNING (MainThread) [custom_components.meross_lan] MerossDevice(2009222728525590831148e1e9343614) error in async_http_request: Server disconnected
2022-02-03 09:51:32 WARNING (MainThread) [custom_components.meross_lan] MerossDevice(2009221363906590831148e1e934418a) error in async_http_request: Server disconnected
2022-02-03 09:51:32 ERROR (SyncWorker_6) [homeassistant.components.google_maps.device_tracker] The cookie file provided does not provide a valid session. Please create another one and try again
2022-02-03 09:51:32 ERROR (MainThread) [homeassistant.components.device_tracker] Error setting up platform legacy google_maps
2022-02-03 09:51:38 WARNING (MainThread) [homeassistant.helpers.entity] Update of camera.xiaomi_cloud_map_extractor is taking over 10 seconds
2022-02-03 09:51:40 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform hildebrandglow_dcc is taking over 10 seconds.
2022-02-03 09:53:52 ERROR (Thread-2) [root] Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.9/logging/handlers.py", line 1518, in _monitor
    self.handle(record)
  File "/usr/local/lib/python3.9/logging/handlers.py", line 1499, in handle
    handler.handle(record)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 952, in handle
    self.emit(record)
  File "/usr/src/homeassistant/homeassistant/components/system_log/__init__.py", line 192, in emit
    entry = LogEntry(record, stack, _figure_out_source(record, stack, self.hass))
  File "/usr/src/homeassistant/homeassistant/components/system_log/__init__.py", line 99, in __init__
    self.message = deque([record.getMessage()], maxlen=5)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 367, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
2022-02-03 09:53:54 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.electric_consumption_today is taking over 10 seconds
2022-02-03 09:53:54 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.gas_consumption_today is taking over 10 seconds
2022-02-03 09:53:54 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.electric_cost_today is taking over 10 seconds
2022-02-03 09:53:54 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.gas_cost_today is taking over 10 seconds
2022-02-03 09:55:26 ERROR (bellows.thread_0) [homeassistant] Error doing job: Exception in callback SerialTransport._call_connection_lost(None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.9/site-packages/serial_asyncio/__init__.py", line 417, in _call_connection_lost
    self._serial.close()
  File "/usr/local/lib/python3.9/site-packages/serial/urlhandler/protocol_socket.py", line 104, in close
    time.sleep(0.3)
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 166, in protected_loop_func
    check_loop(func, strict=strict)
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 129, in check_loop
    raise RuntimeError(
RuntimeError: Detected blocking call inside the event loop. This is causing stability issues. Please report issue
2022-02-03 09:55:54 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.electric_consumption_today is taking over 10 seconds
2022-02-03 09:55:54 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.electric_consumption_year is taking over 10 seconds
2022-02-03 09:55:54 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.electric_tariff_standing is taking over 10 seconds
2022-02-03 09:55:54 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.gas_consumption_today is taking over 10 seconds
2022-02-03 09:55:54 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.gas_consumption_year is taking over 10 seconds
2022-02-03 09:55:54 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.gas_tariff_standing is taking over 10 seconds
2022-02-03 09:55:54 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.electric_cost_today is taking over 10 seconds
2022-02-03 09:55:54 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.gas_cost_today is taking over 10 seconds
2022-02-03 09:57:54 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.electric_consumption_today is taking over 10 seconds
2022-02-03 09:57:54 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.electric_consumption_year is taking over 10 seconds
2022-02-03 09:57:54 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.electric_tariff_standing is taking over 10 seconds
2022-02-03 09:57:54 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.gas_consumption_today is taking over 10 seconds
2022-02-03 09:57:54 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.gas_consumption_year is taking over 10 seconds
2022-02-03 09:57:54 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.gas_tariff_standing is taking over 10 seconds
2022-02-03 09:57:54 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.electric_cost_today is taking over 10 seconds
2022-02-03 09:57:54 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.gas_cost_today is taking over 10 seconds
2022-02-03 09:58:31 WARNING (SyncWorker_23) [custom_components.hildebrandglow_dcc.glow] Error connecting to Glow ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2022-02-03 09:58:31 WARNING (SyncWorker_10) [custom_components.hildebrandglow_dcc.glow] Error connecting to Glow ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2022-02-03 09:59:54 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.electric_consumption_today is taking over 10 seconds
2022-02-03 09:59:54 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.electric_tariff_standing is taking over 10 seconds
2022-02-03 09:59:54 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.gas_consumption_today is taking over 10 seconds
2022-02-03 09:59:54 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.electric_cost_today is taking over 10 seconds
2022-02-03 09:59:54 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.gas_cost_today is taking over 10 seconds
2022-02-03 10:00:32 WARNING (SyncWorker_27) [custom_components.hildebrandglow_dcc.glow] Error connecting to Glow ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2022-02-03 10:00:32 WARNING (SyncWorker_17) [custom_components.hildebrandglow_dcc.glow] Error connecting to Glow ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2022-02-03 10:01:54 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.electric_consumption_today is taking over 10 seconds
2022-02-03 10:01:54 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.electric_consumption_year is taking over 10 seconds
2022-02-03 10:01:54 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.electric_tariff_standing is taking over 10 seconds
2022-02-03 10:01:54 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.gas_consumption_today is taking over 10 seconds
2022-02-03 10:01:54 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.gas_consumption_year is taking over 10 seconds
2022-02-03 10:01:54 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.gas_tariff_standing is taking over 10 seconds
2022-02-03 10:01:54 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.electric_cost_today is taking over 10 seconds
2022-02-03 10:01:54 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.gas_cost_today is taking over 10 seconds
2022-02-03 10:02:14 WARNING (SyncWorker_21) [custom_components.hildebrandglow_dcc.glow] Error connecting to Glow ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2022-02-03 10:02:14 WARNING (SyncWorker_39) [custom_components.hildebrandglow_dcc.glow] Error connecting to Glow ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2022-02-03 10:02:32 WARNING (SyncWorker_38) [custom_components.hildebrandglow_dcc.glow] Error connecting to Glow ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2022-02-03 10:02:33 WARNING (SyncWorker_32) [custom_components.hildebrandglow_dcc.glow] Error connecting to Glow ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2022-02-03 10:02:33 WARNING (SyncWorker_28) [custom_components.hildebrandglow_dcc.glow] Error connecting to Glow ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2022-02-03 10:02:33 WARNING (SyncWorker_3) [custom_components.hildebrandglow_dcc.glow] Error connecting to Glow ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2022-02-03 10:02:54 WARNING (MainThread) [zigpy.appdb] Discarding _save_attribute event
2022-02-03 10:03:44 WARNING (MainThread) [zigpy.appdb] Discarding _save_attribute event
2022-02-03 10:03:54 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.electric_consumption_today is taking over 10 seconds
2022-02-03 10:03:54 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.electric_consumption_year is taking over 10 seconds
2022-02-03 10:03:54 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.electric_tariff_standing is taking over 10 seconds
2022-02-03 10:03:54 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.gas_consumption_today is taking over 10 seconds
2022-02-03 10:03:54 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.gas_consumption_year is taking over 10 seconds
2022-02-03 10:03:54 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.gas_tariff_standing is taking over 10 seconds
2022-02-03 10:03:54 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.electric_cost_today is taking over 10 seconds
2022-02-03 10:03:54 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.gas_cost_today is taking over 10 seconds
2022-02-03 10:04:14 WARNING (SyncWorker_42) [custom_components.hildebrandglow_dcc.glow] Error connecting to Glow ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2022-02-03 10:04:14 WARNING (SyncWorker_0) [custom_components.hildebrandglow_dcc.glow] Error connecting to Glow ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2022-02-03 10:05:54 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.electric_consumption_today is taking over 10 seconds
2022-02-03 10:05:54 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.electric_consumption_year is taking over 10 seconds
2022-02-03 10:05:54 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.electric_tariff_standing is taking over 10 seconds
2022-02-03 10:05:54 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.gas_consumption_today is taking over 10 seconds
2022-02-03 10:05:54 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.gas_consumption_year is taking over 10 seconds
2022-02-03 10:05:54 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.gas_tariff_standing is taking over 10 seconds
2022-02-03 10:05:54 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.electric_cost_today is taking over 10 seconds
2022-02-03 10:05:54 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.gas_cost_today is taking over 10 seconds
2022-02-03 10:06:14 WARNING (SyncWorker_17) [custom_components.hildebrandglow_dcc.glow] Error connecting to Glow ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2022-02-03 10:06:14 WARNING (SyncWorker_20) [custom_components.hildebrandglow_dcc.glow] Error connecting to Glow ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2022-02-03 10:06:14 WARNING (SyncWorker_34) [custom_components.hildebrandglow_dcc.glow] Error connecting to Glow ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2022-02-03 10:07:54 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.electric_consumption_today is taking over 10 seconds
2022-02-03 10:07:54 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.electric_consumption_year is taking over 10 seconds
2022-02-03 10:07:54 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.electric_tariff_standing is taking over 10 seconds
2022-02-03 10:07:54 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.gas_consumption_today is taking over 10 seconds
2022-02-03 10:07:54 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.gas_consumption_year is taking over 10 seconds
2022-02-03 10:07:54 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.gas_tariff_standing is taking over 10 seconds
2022-02-03 10:07:54 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.electric_cost_today is taking over 10 seconds
2022-02-03 10:07:54 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.gas_cost_today is taking over 10 seconds
2022-02-03 10:09:54 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.electric_consumption_today is taking over 10 seconds
2022-02-03 10:09:54 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.electric_consumption_year is taking over 10 seconds
2022-02-03 10:09:54 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.electric_tariff_standing is taking over 10 seconds
2022-02-03 10:09:54 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.gas_consumption_today is taking over 10 seconds
2022-02-03 10:09:54 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.gas_consumption_year is taking over 10 seconds
2022-02-03 10:09:54 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.gas_tariff_standing is taking over 10 seconds
2022-02-03 10:09:54 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.electric_cost_today is taking over 10 seconds
2022-02-03 10:09:54 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.gas_cost_today is taking over 10 seconds
2022-02-03 10:11:54 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.electric_consumption_today is taking over 10 seconds
2022-02-03 10:11:54 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.electric_tariff_standing is taking over 10 seconds
2022-02-03 10:11:54 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.gas_consumption_today is taking over 10 seconds
2022-02-03 10:11:54 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.gas_consumption_year is taking over 10 seconds
2022-02-03 10:11:54 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.gas_tariff_standing is taking over 10 seconds
2022-02-03 10:11:54 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.electric_cost_today is taking over 10 seconds
2022-02-03 10:11:54 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.gas_cost_today is taking over 10 seconds
2022-02-03 10:13:54 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.electric_consumption_today is taking over 10 seconds
2022-02-03 10:13:54 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.electric_tariff_standing is taking over 10 seconds
2022-02-03 10:13:54 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.gas_consumption_today is taking over 10 seconds
2022-02-03 10:13:54 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.electric_cost_today is taking over 10 seconds
2022-02-03 10:13:54 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.gas_cost_today is taking over 10 seconds
2022-02-03 10:15:54 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.electric_consumption_today is taking over 10 seconds
2022-02-03 10:15:54 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.electric_consumption_year is taking over 10 seconds
2022-02-03 10:15:54 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.electric_tariff_standing is taking over 10 seconds
2022-02-03 10:15:54 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.gas_consumption_today is taking over 10 seconds
2022-02-03 10:15:54 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.gas_consumption_year is taking over 10 seconds
2022-02-03 10:15:54 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.gas_tariff_standing is taking over 10 seconds
2022-02-03 10:15:54 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.electric_cost_today is taking over 10 seconds
2022-02-03 10:15:54 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.gas_cost_today is taking over 10 seconds
2022-02-03 10:16:12 ERROR (bellows.thread_0) [homeassistant] Error doing job: Exception in callback SerialTransport._call_connection_lost(None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.9/site-packages/serial_asyncio/__init__.py", line 417, in _call_connection_lost
    self._serial.close()
  File "/usr/local/lib/python3.9/site-packages/serial/urlhandler/protocol_socket.py", line 104, in close
    time.sleep(0.3)
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 166, in protected_loop_func
    check_loop(func, strict=strict)
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 129, in check_loop
    raise RuntimeError(
RuntimeError: Detected blocking call inside the event loop. This is causing stability issues. Please report issue
2022-02-03 10:16:29 WARNING (SyncWorker_18) [custom_components.hildebrandglow_dcc.glow] Error connecting to Glow ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2022-02-03 10:16:29 WARNING (SyncWorker_12) [custom_components.hildebrandglow_dcc.glow] Error connecting to Glow ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2022-02-03 10:16:35 WARNING (MainThread) [zigpy.appdb] Discarding _save_attribute event
2022-02-03 10:17:54 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.electric_consumption_today is taking over 10 seconds
2022-02-03 10:17:54 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.electric_consumption_year is taking over 10 seconds
2022-02-03 10:17:54 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.electric_tariff_standing is taking over 10 seconds
2022-02-03 10:17:54 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.gas_consumption_today is taking over 10 seconds
2022-02-03 10:17:54 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.gas_consumption_year is taking over 10 seconds
2022-02-03 10:17:54 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.gas_tariff_standing is taking over 10 seconds
2022-02-03 10:17:54 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.electric_cost_today is taking over 10 seconds
2022-02-03 10:17:54 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.gas_cost_today is taking over 10 seconds
2022-02-03 10:18:29 WARNING (SyncWorker_18) [custom_components.hildebrandglow_dcc.glow] Error connecting to Glow ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2022-02-03 10:18:29 WARNING (SyncWorker_37) [custom_components.hildebrandglow_dcc.glow] Error connecting to Glow ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2022-02-03 10:18:29 WARNING (SyncWorker_0) [custom_components.hildebrandglow_dcc.glow] Error connecting to Glow ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2022-02-03 10:19:54 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.electric_consumption_today is taking over 10 seconds
2022-02-03 10:19:54 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.electric_consumption_year is taking over 10 seconds
2022-02-03 10:19:54 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.electric_tariff_standing is taking over 10 seconds
2022-02-03 10:19:54 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.gas_consumption_today is taking over 10 seconds
2022-02-03 10:19:54 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.gas_consumption_year is taking over 10 seconds
2022-02-03 10:19:54 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.gas_tariff_standing is taking over 10 seconds
2022-02-03 10:19:54 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.electric_cost_today is taking over 10 seconds
2022-02-03 10:19:54 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.gas_cost_today is taking over 10 seconds
2022-02-03 10:20:30 WARNING (SyncWorker_13) [custom_components.hildebrandglow_dcc.glow] Error connecting to Glow ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2022-02-03 10:20:30 WARNING (SyncWorker_5) [custom_components.hildebrandglow_dcc.glow] Error connecting to Glow ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2022-02-03 10:20:30 WARNING (SyncWorker_1) [custom_components.hildebrandglow_dcc.glow] Error connecting to Glow ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2022-02-03 10:20:30 WARNING (SyncWorker_12) [custom_components.hildebrandglow_dcc.glow] Error connecting to Glow ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2022-02-03 10:21:54 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.electric_consumption_today is taking over 10 seconds
2022-02-03 10:21:54 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.electric_consumption_year is taking over 10 seconds
2022-02-03 10:21:54 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.electric_tariff_standing is taking over 10 seconds
2022-02-03 10:21:54 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.gas_consumption_today is taking over 10 seconds
2022-02-03 10:21:54 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.gas_consumption_year is taking over 10 seconds
2022-02-03 10:21:54 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.gas_tariff_standing is taking over 10 seconds
2022-02-03 10:21:54 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.electric_cost_today is taking over 10 seconds
2022-02-03 10:21:54 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.gas_cost_today is taking over 10 seconds
2022-02-03 10:22:14 WARNING (SyncWorker_47) [custom_components.hildebrandglow_dcc.glow] Error connecting to Glow ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2022-02-03 10:22:14 WARNING (SyncWorker_13) [custom_components.hildebrandglow_dcc.glow] Error connecting to Glow ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2022-02-03 10:22:14 WARNING (SyncWorker_17) [custom_components.hildebrandglow_dcc.glow] Error connecting to Glow ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2022-02-03 10:23:54 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.electric_consumption_today is taking over 10 seconds
2022-02-03 10:23:54 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.electric_consumption_year is taking over 10 seconds
2022-02-03 10:23:54 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.electric_tariff_standing is taking over 10 seconds
2022-02-03 10:23:54 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.gas_consumption_today is taking over 10 seconds
2022-02-03 10:23:54 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.gas_consumption_year is taking over 10 seconds
2022-02-03 10:23:54 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.gas_tariff_standing is taking over 10 seconds
2022-02-03 10:23:54 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.electric_cost_today is taking over 10 seconds
2022-02-03 10:23:54 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.gas_cost_today is taking over 10 seconds

**Comment by ColinRobbins** [comment] 2022-02-03 10:45
There are ongoing issues at the Glow end.

https://forum.glowmarkt.com/index.php?p=/discussion/129/bright-outage-including-apis-and-mqtt#latest

**Comment by ColinRobbins** [comment] 2022-02-07 19:01
See https://github.com/HandyHat/ha-hildebrandglow-dcc/issues/126#issuecomment-1031810136

**Comment by ColinRobbins** [comment] 2022-02-08 19:12
It seems to be working for me now - glow have fixed it.

**Comment by thorrrr** [comment] 2022-02-08 19:21
Did you say they were going to end it?

**Comment by si458** [comment] 2022-02-09 12:55
> Did you say they were going to end it?

@thorrrr GlowMarkt are continuing to support there API from the reports on the forums and via emails,
i believe you can close this issue now

**Comment by thorrrr** [comment] 2022-02-09 12:57
Seems to be working fine now

**Closed** 2022-02-09 12:57 UTC
Labels: bug

**Comment by HandyHat** [comment] 2022-02-22 23:40
Duplicate of #126
