### ISSUE TITLE
Custom Component not showing after manual install

### ISSUE THREAD

**Issue by harvybob** [HandyHat/ha-hildebrandglow-dcc#246] opened 2022-08-25 07:04 UTC
**Describe the bug**
I have a VM image running HASSIO + HA, I have copied in the folder following the manual install steps, and restarted both HA and HASSIO, but the integration still is not available.

**To Reproduce**
Steps to reproduce the behaviour:

Copied custom_components/hildebrandglow_dcc/ to config/custom_components
(note custom_components did not exist so needed to be created - I have no other custom_components)

Restarted HA/HASSIO

Select settings
select Integrations
select devices and services
add integrations
search string "hil", "solar", "DCC" etc bring back no results

**Expected behaviour**
When searching, expect to see result for Hildebrand and install integration

**Screenshots**
Files in the folder as per readme manual install steps
![image](https://user-images.githubusercontent.com/17744328/186596946-4cf4be76-5e56-42c0-bd63-45b687ecb769.png)
![image](https://user-images.githubusercontent.com/17744328/186597172-aa0b07aa-8eae-445e-abfc-636c32a9b205.png)

**Version**
What version of the integration and what version of Home Assistant are you running?
Home Assistant 2022.8.6
Supervisor 2022.08.3
Operating System 8.5
Frontend 20220802.0 - latest
Integration: v0.6.0 (downloaded fresh on 23rd Aug

**Debug log**
Enable debug logging by following the instructions [here](https://github.com/HandyHat/ha-hildebrandglow-dcc#debugging)

**Additional context**
I appreciate this may be an issue with the method /steps I have taken to install the custom component, so any guidance on what I may have done wrong is appreciated (and hopefully update the readme so others don't make the same mistakes?)

**Comment by liblikas90** [comment] 2022-08-25 22:22
Finding same issue when installing automatically via HACS too

**Comment by NilSkilz** [comment] 2022-09-01 20:34
I'm getting the same result when installing via HACS.

**Comment by NilSkilz** [comment] 2022-09-01 20:42
> I'm getting the same result when installing via HACS.

I was using the Mac Home Assistant App. Once I switched to using a browser the integration appeared. Potentially an issue with the native app rather than the integration. Hope this helps.

**Comment by dmlambert99** [comment] 2022-09-02 01:52
Just setup a new system with fresh installs 
Home Assistant 2022.8.7
Supervisor 2022.08.5
Operating System 8.5
Frontend 20220802.0 - latest
Had same issue in web app that could not find the integration after installing via HACS. However, after reading comments here I installed the iOS app and was able to add the integration there.
Also noticed that the HACS install puts the files in the folder "hildebrandglow_dcc" within custom_components, I don't know if that matters.

**Comment by digdilem** [comment] 2022-09-02 19:42
Same here, installed via HACS. It just doesn't show up in the integrations, unlike several others I've installed with the same method.

**Comment by HandyHat** [comment] 2022-09-02 20:26
Hey all,
Once you add a custom integration to your `custom_components` folder, you have to clear your browser cache for the integration to appear in the list. A lot of people seem to run into this so I will definitely add it to the readme.

Duplicate of #34

**Closed by HandyHat** 2022-09-02 20:26 UTC
Labels: bug

**Comment by harvybob** [comment] 2022-09-05 09:48
Just to update, I created a hildebrandglow_dcc folder in custom components that that has worked for me.
So just to clarify, this is the tree:

![image](https://user-images.githubusercontent.com/17744328/188420526-9ae9306b-9b45-4a98-8f66-0d3443815ccb.png)

I think the readme asks to put the files straight into the custom_components folder rather then move the hildebrandglow_dcc folder into it!
