### ISSUE TITLE
sensor state class 'total_increasing' is invalid for 'monetary' values

### ISSUE THREAD

**Issue by Achronite** [HandyHat/ha-hildebrandglow-dcc#322] opened 2023-03-28 09:20 UTC
**Describe the bug**
The sensors `dcc_sourced_smart_gas_meter_cost_today` and `dcc_sourced_smart_electricity_meter_cost_today` are incorrectly defined within HA due to incompatibility between state 'total_increasing' and device class 'monetary'.
e.g.
`Entity sensor.dcc_sourced_smart_gas_meter_cost_today (<class 'custom_components.hildebrandglow_dcc.sensor.Cost'>) is using state class 'total_increasing' which is impossible considering device class ('monetary') it is using; expected None or one of 'total'`

**To Reproduce**
Restart HA, look at system logs.

**Expected behaviour**
DCC sensors should to be defined correctly within HA to operate correctly

**Screenshots**
From system logs (HA Core v2023.3.6)
Logger: homeassistant.components.sensor
Source: components/sensor/__init__.py:497
Integration: Sensor ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
First occurred: 10:00:36 (2 occurrences)
Last logged: 10:00:37

-  Entity sensor.dcc_sourced_smart_gas_meter_cost_today (<class 'custom_components.hildebrandglow_dcc.sensor.Cost'>) is using state class 'total_increasing' which is impossible considering device class ('monetary') it is using; expected None or one of 'total'; Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.
- Entity sensor.dcc_sourced_smart_electricity_meter_cost_today (<class 'custom_components.hildebrandglow_dcc.sensor.Cost'>) is using state class 'total_increasing' which is impossible considering device class ('monetary') it is using; expected None or one of 'total'; Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.

**Version**
v1.0.3
HA Core v2023.3.6

**Debug log**
Not required

**Additional context**
Problem reported at startup of HA

**Comment by HandyHat** [comment] 2023-04-01 15:20
Hey @Achronite, it looks like this is the same issue as #304. Feel free to follow that issue!

Duplicate of #304

**Closed by HandyHat** 2023-04-01 15:20 UTC
Labels: bug
