### ISSUE TITLE
Electrical Energy Usage Not Reporting Properly

### ISSUE THREAD

**Issue by clampatron** [HandyHat/ha-hildebrandglow-dcc#270] opened 2022-11-24 12:47 UTC
Installed integration on the 23/11/22
Stats shown by integration sensors in Lovelace
![image](https://user-images.githubusercontent.com/6141941/203786566-5102c583-5e4e-4441-bcf8-6fe5ac08d9b9.png)
~24hr history
![image](https://user-images.githubusercontent.com/6141941/203786888-d0f100ba-af84-4ad6-a58a-1d8bbe4031fa.png)
Energy Dashboard
Setup
![image](https://user-images.githubusercontent.com/6141941/203842680-53586b57-3a4e-465b-9769-dd96531a2356.png)
Bad stats
![image](https://user-images.githubusercontent.com/6141941/203787827-3daab1a4-0b49-4287-ac5b-cf39f15fb8d6.png)
Actual data 
![image](https://user-images.githubusercontent.com/6141941/203796523-e08ffb50-fc15-4144-b0d3-fa8328dc35cb.png)

**Comment by HandyHat** [comment] 2023-01-01 17:12
This should be fixed as of v1.0.0

Duplicate of #227

**Closed by HandyHat** 2023-01-01 17:12 UTC
