### ISSUE TITLE
Data in Bright and HA not the same

### ISSUE THREAD

**Issue by smcfadden** [HandyHat/ha-hildebrandglow-dcc#313] opened 2023-02-17 18:57 UTC
![Screenshot_20230217_185130_Home Assistant](https://user-images.githubusercontent.com/5184751/219759402-5a4250e3-43cf-4f18-9302-2364687d60ce.jpg)
![Screenshot_20230217_185055_Bright](https://user-images.githubusercontent.com/5184751/219759444-68cce679-10cf-4a86-8122-b4ff06c06966.jpg)
Two images showing similar views in Bright and Home Assistant. Have I missed something. Downloaded earlier this week. Thanks

**Comment by HandyHat** [comment] 2023-02-17 23:57
Hey @smcfadden, this looks like it may be the same issue as #305. Feel free to follow and add to the discussion there!

Duplicate of #305

**Closed** 2023-02-17 23:57 UTC
