### ISSUE TITLE
Re Auth Sign In

### ISSUE THREAD

**Issue by thorrrr** [HandyHat/ha-hildebrandglow-dcc#258] opened 2022-10-21 13:54 UTC
HI is there a way to log out and re log back  into the integration ?

**Comment by thorrrr** [comment] 2022-10-21 15:58
The problem
No Energy Data for 7 days but my Bright App shows it!!
Also logs provided via debug

Logger: homeassistant.components.sensor
Source: custom_components/hildebrandglow_dcc/glow.py:52
Integration: Sensor (documentation, issues)
First occurred: 08:52:09 (1 occurrences)
Last logged: 08:52:09

Error while setting up hildebrandglow_dcc platform for sensor
Traceback (most recent call last):
File "/config/custom_components/hildebrandglow_dcc/sensor.py", line 50, in async_setup_entry
resources = await hass.async_add_executor_job(glow.retrieve_resources)
File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/hildebrandglow_dcc/glow.py", line 91, in retrieve_resources
raise InvalidAuth
custom_components.hildebrandglow_dcc.glow.InvalidAuth

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
await asyncio.shield(task)
File "/config/custom_components/hildebrandglow_dcc/sensor.py", line 54, in async_setup_entry
await Glow.handle_failed_auth(config, hass)
File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/hildebrandglow_dcc/glow.py", line 52, in authenticate
if data["valid"]:
KeyError: 'valid'

What version of Home Assistant Core has the issue?
Home Assistant 2022.10.5 Supervisor 2022.10.0 Operating System 9.2 Frontend 20221010.0 - latest

What was the last working version of Home Assistant Core?
No response

What type of installation are you running?
Home Assistant Supervised

Integration causing the issue
hildebrandglow_dcc/glow

Link to integration documentation on our website
https://github.com/HandyHat/ha-hildebrandglow-dcc

Diagnostics information
No response

Example YAML snippet
No response

Anything in the logs that might be useful for us?
No response

Additional information
No response

**Comment by ColinRobbins** [comment] 2022-11-04 20:08
Remove the integration, and re-add?
Sensors should come back with same names etc.

**Comment by HandyHat** [comment] 2023-01-01 13:30
Duplicate of #121

**Closed by HandyHat** 2023-01-01 13:30 UTC
